/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error': '#fff7f6',
        'tertiary-container': '#fceab9',
        'surface-tint': '#885200',
        'surface-bright': '#f9f9f9',
        'on-secondary-fixed-variant': '#5c5b5b',
        'on-primary-fixed': '#5d3700',
        error: '#9e422c',
        'on-surface-variant': '#5f5f5f',
        'error-dim': '#5c1202',
        'tertiary-dim': '#5e522d',
        'secondary-container': '#e5e2e1',
        'primary-container': '#ffddbb',
        'surface-dim': '#dadada',
        primary: '#885200',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#d6d4d3',
        'surface-container-high': '#e8e8e8',
        outline: '#7b7b7b',
        'on-tertiary': '#fff8ee',
        'surface-container-highest': '#e2e2e2',
        'primary-fixed-dim': '#ffcb93',
        'primary-fixed': '#ffddbb',
        'error-container': '#fe8b70',
        surface: '#f9f9f9',
        'on-surface': '#323232',
        'inverse-on-surface': '#9d9d9d',
        'inverse-surface': '#0e0e0e',
        'surface-container': '#eeeeee',
        secondary: '#605f5f',
        'on-secondary': '#fbf8f8',
        'tertiary-fixed': '#fceab9',
        'on-tertiary-fixed-variant': '#6d6039',
        'secondary-dim': '#545353',
        'outline-variant': '#b2b2b2',
        'on-primary': '#fff6f0',
        background: '#f9f9f9',
        'surface-variant': '#e2e2e2',
        'on-tertiary-container': '#625630',
        'inverse-primary': '#fea93e',
        'tertiary-fixed-dim': '#eddcac',
        'secondary-fixed': '#e5e2e1',
        tertiary: '#6b5e38',
        'on-secondary-fixed': '#403f3f',
        'on-tertiary-fixed': '#4f4420',
        'surface-container-low': '#f3f3f3',
        'on-error-container': '#742410',
        'on-background': '#323232',
        'on-secondary-container': '#525151',
        'on-primary-fixed-variant': '#845000',
        'on-primary-container': '#764700',
        'primary-dim': '#774800',
      },
      borderRadius: {
        DEFAULT: '0rem',
        lg: '0rem',
        xl: '0rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Newsreader', 'serif'],
        label: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
